apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zvcnhahiz-go 
  janus-idp.io/tekton: zvcnhahiz-go
  backstage.io/kubernetes-id: zvcnhahiz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvcnhahiz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml